title:              "Digital Marketer's Note"
tagline:            "Digital Marketing & Adobe Analytics Guide"
email:              "ayoungshin0728@gmail.com"
description:        "블로그 설명"
author:             "신아영"
baseurl:            "/"
url:                "https://ayoungshin.com"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpg"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# 블로그 disqus shortname
disqus:
  shortname: ayoungshin-com

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
